import { useEffect, useState } from 'react';
import DashboardLayout from '@/components/dashboard/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth-context';
import { toast } from 'sonner';
import { Plus, Users, Trash2, UserPlus, Copy, ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';

interface Student {
  id: string;
  first_name: string;
  student_code: string;
  created_at: string;
}

interface Group {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  students?: Student[];
}

export default function Groups() {
  const { user } = useAuth();
  const [groups, setGroups] = useState<Group[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedGroup, setExpandedGroup] = useState<string | null>(null);
  const [newGroupOpen, setNewGroupOpen] = useState(false);
  const [newStudentOpen, setNewStudentOpen] = useState<string | null>(null);

  useEffect(() => {
    if (user) {
      loadGroups();
    }
  }, [user]);

  const loadGroups = async () => {
    if (!user) return;
    
    try {
      // Explicitly filter by teacher_id to ensure data isolation
      const { data: groupsData, error } = await supabase
        .from('groups')
        .select('*')
        .eq('teacher_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;

      // Load students for each group
      const groupsWithStudents = await Promise.all(
        (groupsData || []).map(async (group) => {
          const { data: students } = await supabase
            .from('students')
            .select('*')
            .eq('group_id', group.id)
            .order('created_at', { ascending: true });
          return { ...group, students: students || [] };
        })
      );

      setGroups(groupsWithStudents);
    } catch (error) {
      console.error('Error loading groups:', error);
      toast.error('Failed to load groups');
    } finally {
      setLoading(false);
    }
  };

  const createGroup = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const name = formData.get('name') as string;
    const description = formData.get('description') as string;

    try {
      const { error } = await supabase.from('groups').insert({
        name,
        description: description || null,
        teacher_id: user?.id,
      });

      if (error) throw error;

      toast.success('Group created successfully!');
      setNewGroupOpen(false);
      loadGroups();
    } catch (error: any) {
      toast.error(error.message || 'Failed to create group');
    }
  };

  const deleteGroup = async (groupId: string) => {
    if (!confirm('Are you sure? This will delete all students in this group.')) return;

    try {
      const { error } = await supabase.from('groups').delete().eq('id', groupId);
      if (error) throw error;

      toast.success('Group deleted');
      loadGroups();
    } catch (error: any) {
      toast.error(error.message || 'Failed to delete group');
    }
  };

  const addStudent = async (e: React.FormEvent<HTMLFormElement>, groupId: string) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const firstName = formData.get('firstName') as string;

    try {
      const { error } = await supabase.from('students').insert({
        first_name: firstName,
        group_id: groupId,
        student_code: '', // Will be auto-generated by trigger
      });

      if (error) throw error;

      toast.success('Student added successfully!');
      setNewStudentOpen(null);
      loadGroups();
    } catch (error: any) {
      toast.error(error.message || 'Failed to add student');
    }
  };

  const deleteStudent = async (studentId: string) => {
    if (!confirm('Delete this student?')) return;

    try {
      const { error } = await supabase.from('students').delete().eq('id', studentId);
      if (error) throw error;

      toast.success('Student deleted');
      loadGroups();
    } catch (error: any) {
      toast.error(error.message || 'Failed to delete student');
    }
  };

  const copyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    toast.success('Code copied!');
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold">Groups</h1>
            <p className="text-muted-foreground">Manage your classes</p>
          </div>
          <Dialog open={newGroupOpen} onOpenChange={setNewGroupOpen}>
            <DialogTrigger asChild>
              <Button className="gradient-primary btn-bounce">
                <Plus className="w-4 h-4 mr-2" />
                New Group
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Group</DialogTitle>
              </DialogHeader>
              <form onSubmit={createGroup} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Group Name</Label>
                  <Input id="name" name="name" placeholder="e.g. Grade 10 - ICT" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="description">Description (Optional)</Label>
                  <Input id="description" name="description" placeholder="Class description" />
                </div>
                <Button type="submit" className="w-full gradient-primary">Create Group</Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        {/* Groups List */}
        {loading ? (
          <div className="text-center py-12 text-muted-foreground">Loading...</div>
        ) : groups.length === 0 ? (
          <Card className="card-elevated">
            <CardContent className="py-12 text-center">
              <Users className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
              <h3 className="text-lg font-semibold mb-2">No groups yet</h3>
              <p className="text-muted-foreground mb-4">Create your first class group to get started</p>
              <Button onClick={() => setNewGroupOpen(true)} className="gradient-primary btn-bounce">
                <Plus className="w-4 h-4 mr-2" />
                Create Group
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            {groups.map((group, index) => (
              <Card 
                key={group.id} 
                className="card-elevated animate-slide-up"
                style={{ animationDelay: `${index * 50}ms` }}
              >
                <CardHeader 
                  className="cursor-pointer"
                  onClick={() => setExpandedGroup(expandedGroup === group.id ? null : group.id)}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 rounded-xl bg-primary flex items-center justify-center">
                        <Users className="w-6 h-6 text-primary-foreground" />
                      </div>
                      <div>
                        <CardTitle className="text-lg">{group.name}</CardTitle>
                        <p className="text-sm text-muted-foreground">
                          {group.students?.length || 0} students
                          {group.description && ` • ${group.description}`}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="text-destructive hover:bg-destructive/10"
                        onClick={(e) => { e.stopPropagation(); deleteGroup(group.id); }}
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                      {expandedGroup === group.id ? (
                        <ChevronUp className="w-5 h-5 text-muted-foreground" />
                      ) : (
                        <ChevronDown className="w-5 h-5 text-muted-foreground" />
                      )}
                    </div>
                  </div>
                </CardHeader>
                
                {expandedGroup === group.id && (
                  <CardContent className="border-t border-border pt-4">
                    <div className="flex justify-between items-center mb-4">
                      <h4 className="font-medium">Students</h4>
                      <Dialog open={newStudentOpen === group.id} onOpenChange={(open) => setNewStudentOpen(open ? group.id : null)}>
                        <DialogTrigger asChild>
                          <Button size="sm" variant="outline" className="btn-bounce">
                            <UserPlus className="w-4 h-4 mr-2" />
                            Add Student
                          </Button>
                        </DialogTrigger>
                        <DialogContent>
                          <DialogHeader>
                            <DialogTitle>Add Student to {group.name}</DialogTitle>
                          </DialogHeader>
                          <form onSubmit={(e) => addStudent(e, group.id)} className="space-y-4">
                            <div className="space-y-2">
                              <Label htmlFor="firstName">First Name</Label>
                              <Input id="firstName" name="firstName" placeholder="Student's first name" required />
                            </div>
                            <p className="text-sm text-muted-foreground">
                              A unique access code will be generated automatically.
                            </p>
                            <Button type="submit" className="w-full gradient-primary">Add Student</Button>
                          </form>
                        </DialogContent>
                      </Dialog>
                    </div>

                    {group.students && group.students.length > 0 ? (
                      <div className="space-y-2">
                        {group.students.map((student) => (
                          <div 
                            key={student.id}
                            className="flex items-center justify-between p-3 rounded-xl bg-muted/50 hover:bg-muted transition-colors"
                          >
                            <div className="flex items-center gap-3">
                              <div className="w-8 h-8 rounded-lg bg-secondary flex items-center justify-center text-secondary-foreground font-bold text-sm">
                                {student.first_name.charAt(0).toUpperCase()}
                              </div>
                              <span className="font-medium">{student.first_name}</span>
                            </div>
                            <div className="flex items-center gap-2">
                              <code className="px-3 py-1 rounded-lg bg-primary/10 text-primary font-mono text-sm">
                                {student.student_code}
                              </code>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={() => copyCode(student.student_code)}
                              >
                                <Copy className="w-3 h-3" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8 text-destructive hover:bg-destructive/10"
                                onClick={() => deleteStudent(student.id)}
                              >
                                <Trash2 className="w-3 h-3" />
                              </Button>
                            </div>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <p className="text-center py-6 text-muted-foreground">
                        No students yet. Add students to this group.
                      </p>
                    )}
                  </CardContent>
                )}
              </Card>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
